In [1]:
# Fake News Classifier using Bi-Directional LSTM

In [3]:
# Importing pandas
import pandas as pd
df = pd.read_csv('train.csv')

In [4]:
# Viewing records
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [5]:
# Seeing any null values
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
# Dropping null values
df = df.dropna()

In [7]:
# Viewing records
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [10]:
# Get the independent features
X = df.drop('label', axis = 1)

In [14]:
# Get the dependent features
Y = df['label']

In [12]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [17]:
Y, Y.value_counts()

(0        1
 1        0
 2        1
 3        1
 4        1
         ..
 20795    0
 20796    0
 20797    0
 20798    1
 20799    1
 Name: label, Length: 18285, dtype: int64,
 label
 0    10361
 1     7924
 Name: count, dtype: int64)

In [20]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [64]:
# Importing tensorflow

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [65]:
# Vocabulary size
voc_size = 5000

In [66]:
message = X.copy()
message

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [67]:
import nltk
import re
from nltk.corpus import stopwords

In [68]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Kaushik\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [69]:
message.reset_index(inplace = True)

In [70]:
# Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['title'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [71]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [72]:
# One-Hot Representation
onehot_repr = [one_hot(words, voc_size) for words in corpus]
onehot_repr

[[4766, 4729, 557, 4287, 4881, 1058, 884, 4091, 2801, 4024],
 [3198, 3424, 479, 22, 2158, 3507, 1807],
 [3609, 4301, 3866, 192],
 [4614, 2207, 2501, 1122, 4128, 80],
 [4707, 2158, 2749, 703, 1835, 199, 2158, 4013, 200, 4159],
 [4132,
  3330,
  2692,
  311,
  3493,
  1208,
  1019,
  3543,
  3306,
  1714,
  83,
  4351,
  469,
  2368,
  1807],
 [1053, 2792, 255, 4024, 346, 3740, 1106, 1783, 4908, 1803, 2865],
 [2319, 3049, 4205, 4227, 4799, 3205, 1208, 4791, 4908, 1803, 2865],
 [3416, 1318, 2216, 2323, 922, 3540, 2047, 1855, 1208, 3665],
 [4488, 2096, 3717, 3777, 3628, 4327, 4904, 4847],
 [1615, 499, 4870, 1004, 4060, 4387, 2157, 2755, 4553, 2849, 3994],
 [1122, 4550, 4881, 3540, 1208, 4799],
 [141, 753, 3712, 2991, 4003, 3058, 880, 2343, 4071],
 [2197, 4689, 4046, 4181, 4923, 1241, 926, 4908, 1803, 2865],
 [4132, 4891, 4840, 1975, 2731, 4908, 1803, 2865],
 [2433, 2270, 2956, 456, 3882, 4779, 1778, 659, 2496, 4355],
 [1802, 841, 3424],
 [2455, 3989, 3437, 939, 1208, 3511, 1231, 1807],
 [4

In [73]:
# Embedding Representation
sent_length = 20

In [74]:
# Padding   
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
embedded_docs

array([[   0,    0,    0, ..., 4091, 2801, 4024],
       [   0,    0,    0, ..., 2158, 3507, 1807],
       [   0,    0,    0, ..., 4301, 3866,  192],
       ...,
       [   0,    0,    0, ..., 4908, 1803, 2865],
       [   0,    0,    0, ..., 1946, 4636,  603],
       [   0,    0,    0, ...,  744, 2638,  495]])

In [82]:
# Creating the model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirection  (None, 200)               112800    
 al)                                                             
                                                                 
 dense_2 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313001 (1.19 MB)
Trainable params: 313001 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [84]:
# Converting the list into numpy array
import numpy as np
X_final = np.array(embedded_docs)
Y_final = np.array(Y)

In [85]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_final, Y_final, test_size = 0.33, random_state = 42)

In [105]:
# Training the model
history = model.fit(X_train, Y_train, validation_split = 0.33, epochs = 10, batch_size = 50)

Epoch 1/10
165/165 [==============================] - 2s 14ms/step - loss: 4.8883e-09 - accuracy: 1.0000 - val_loss: 1.4091 - val_accuracy: 0.9147
Epoch 2/10
165/165 [==============================] - 2s 14ms/step - loss: 4.7775e-09 - accuracy: 1.0000 - val_loss: 1.4117 - val_accuracy: 0.9149
Epoch 3/10
165/165 [==============================] - 2s 14ms/step - loss: 4.5911e-09 - accuracy: 1.0000 - val_loss: 1.4144 - val_accuracy: 0.9147
Epoch 4/10
165/165 [==============================] - 2s 13ms/step - loss: 4.5610e-09 - accuracy: 1.0000 - val_loss: 1.4164 - val_accuracy: 0.9149
Epoch 5/10
165/165 [==============================] - 2s 13ms/step - loss: 4.4261e-09 - accuracy: 1.0000 - val_loss: 1.4187 - val_accuracy: 0.9152
Epoch 6/10
165/165 [==============================] - 2s 13ms/step - loss: 4.3698e-09 - accuracy: 1.0000 - val_loss: 1.4210 - val_accuracy: 0.9152
Epoch 7/10
165/165 [==============================] - 2s 13ms/step - loss: 4.2934e-09 - accuracy: 1.0000 - val_loss: 1

In [109]:
y_pred = model.predict(X_test)
y_pred

189/189 [==============================] - 1s 4ms/step


array([[1.0000000e+00],
       [3.8144914e-09],
       [2.3158121e-10],
       ...,
       [5.5780798e-09],
       [1.0000000e+00],
       [1.8337594e-01]], dtype=float32)

In [110]:
y_pred = np.where(y_pred > 0.5, 1, 0)
y_pred

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [111]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, y_pred)

array([[3095,  324],
       [ 238, 2378]], dtype=int64)

In [126]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, y_pred)
accuracy

0.9068765534382767